version: '3.3'

services:

  ms-auth:
    volumes:
      - ./data/:/usr/src/app/data
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    restart: always
    env_file:
      - ./ms-auth/.env